export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CARD_ROUTE = '/card'
export const DEVICES_ROUTE = '/devices'
export const USERS_ROUTE = '/users'
